version: '1.0.0'
apiVersion: v3.1.0
kind: DataContract
id: 87d05b19-4a56-40ea-93bc-e58a3481b759
status: active
name: raw_stores
domain: ecommerce
tenant: jaffleshop

description:
  purpose: Raw store/location data ingested from source systems

schema:
  - name: raw_stores
    description: Raw store location data from Jaffle Shop source systems
    physicalName: raw.stores
    logicalType: object
    properties:
      - name: id
        description: Unique store identifier
        logicalType: string
        physicalType: VARCHAR
        required: true
        primaryKey: true
      - name: name
        description: Store display name
        logicalType: string
        physicalType: VARCHAR
        required: true
      - name: opened_at
        description: Date store opened
        logicalType: timestamp
        physicalType: TIMESTAMP
        required: false
      - name: tax_rate
        description: Store tax rate as decimal
        logicalType: number
        physicalType: DOUBLE
        required: false

customProperties:
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359

tags:
  - raw
  - stores
  - dm_level:Bronze
