version: '1.0.0'
apiVersion: v3.1.0
kind: DataContract
id: 9931fece-ad3b-46ad-8872-10ae4327501a
status: active
name: stg_locations
domain: ecommerce
tenant: jaffleshop

description:
  purpose: Staged store location data with standardized attributes

schema:
  - name: stg_locations
    description: Cleaned and standardized location data from raw stores
    physicalName: staging.stg_locations
    logicalType: object
    properties:
      - name: location_id
        description: Standardized location identifier
        logicalType: string
        physicalType: VARCHAR
        required: true
        primaryKey: true
      - name: location_name
        description: Location display name
        logicalType: string
        physicalType: VARCHAR
        required: true
      - name: opened_date
        description: Date location opened
        logicalType: date
        physicalType: DATE
        required: false
      - name: tax_rate
        description: Location tax rate as decimal
        logicalType: number
        physicalType: DOUBLE
        required: false

customProperties:
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359

tags:
  - staging
  - locations
  - dm_level:Silver
