/**
 * SDK/WASM Loader
 * Loads and initializes the data-modelling-sdk WASM module
 */

// SDK module type definition (will be generated by wasm-pack)
interface SDKModule {
  // Placeholder - actual methods will be defined when SDK is available
  init(): Promise<void>;
  // Add SDK methods as they become available
}

class SDKLoader {
  private module: SDKModule | null = null;
  private loadingPromise: Promise<SDKModule> | null = null;

  /**
   * Load the SDK WASM module
   */
  async load(): Promise<SDKModule> {
    if (this.module) {
      return this.module;
    }

    if (this.loadingPromise) {
      return this.loadingPromise;
    }

    this.loadingPromise = this._loadModule();
    this.module = await this.loadingPromise;
    return this.module;
  }

  /**
   * Internal method to load the WASM module
   */
  private async _loadModule(): Promise<SDKModule> {
    try {
      // Load WASM module from SDK pkg directory
      // The pkg directory should be copied to frontend/public/wasm/ during build
      // Using dynamic import with string literal to avoid TypeScript errors
      const wasmPath = '/wasm/data_modelling_sdk.js';
      const wasmModule = await import(/* @vite-ignore */ wasmPath);
      if (wasmModule.default) {
        await wasmModule.default();
      }
      return wasmModule as SDKModule;
    } catch (error) {
      // Fallback: Try relative path (for development)
      try {
        const wasmPath = '../../../../data-modelling-sdk/pkg/data_modelling_sdk.js';
        const wasmModule = await import(/* @vite-ignore */ wasmPath);
        if (wasmModule.default) {
          await wasmModule.default();
        }
        return wasmModule as SDKModule;
      } catch (fallbackError) {
        console.warn('SDK WASM module not available - offline mode will use placeholders');
        console.warn('Build the SDK with: cd ../data-modelling-sdk && wasm-pack build --target web --out-dir pkg --features wasm');
        console.warn('Then copy pkg/ to frontend/public/wasm/');
        // Return placeholder for now - actual SDK methods will be called when available
        return {
          init: async () => {
            console.log('SDK placeholder initialized - WASM module not loaded');
          },
        } as SDKModule;
      }
    }
  }

  /**
   * Get the loaded SDK module
   */
  getModule(): SDKModule | null {
    return this.module;
  }

  /**
   * Check if SDK is loaded
   */
  isLoaded(): boolean {
    return this.module !== null;
  }

  /**
   * Reset the loader (for testing)
   */
  reset(): void {
    this.module = null;
    this.loadingPromise = null;
  }
}

// Export singleton instance
export const sdkLoader = new SDKLoader();

